import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // Main documentation sidebar
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Context Guide',
      collapsed: false,
      items: [
        'context-guide/overview',
        'context-guide/claude-md',
        'context-guide/clear-instructions',
        'context-guide/file-references',
        'context-guide/examples-patterns',
        'context-guide/constraints-boundaries',
        'context-guide/success-criteria',
        'context-guide/advanced-techniques',
      ],
    },
    {
      type: 'category',
      label: 'Analysis',
      items: [
        'analysis/agent-format',
        'analysis/workflow-patterns',
        'analysis/claude-documentation',
      ],
    },
    {
      type: 'category',
      label: 'Design',
      items: [
        'design/architecture',
        'design/agent-selection',
        'design/context-management',
      ],
    },
    {
      type: 'category',
      label: 'Implementation',
      items: [
        'implementation/workflow-creator-agent',
      ],
    },
    {
      type: 'category',
      label: 'Tutorial Basics',
      items: [{type: 'autogenerated', dirName: 'tutorial-basics'}],
    },
    {
      type: 'category',
      label: 'Tutorial Extras',
      items: [{type: 'autogenerated', dirName: 'tutorial-extras'}],
    },
  ],
};

export default sidebars;
